- id: '1602467695537'
  alias: Kveikja ljós í forstofu
  description: ''
  trigger:
  - type: motion
    platform: device
    device_id: e06695130c2c11eba7841d160ecfc3bf
    entity_id: binary_sensor.forstofa_hreyfiskynjari
    domain: binary_sensor
    for:
      hours: 0
      minutes: 0
      seconds: 0
  condition:
  - condition: time
    after: '7:00'
    before: '22:00'
  action:
  - type: turn_on
    device_id: 46de38061f6b11eb876355d2445a994b
    entity_id: switch.shelly_shsw_1_8caab50562b4
    domain: switch
  mode: single
- id: '1602468561310'
  alias: Slökkva ljós í forstofu
  description: ''
  trigger:
  - type: no_motion
    platform: device
    device_id: e06695130c2c11eba7841d160ecfc3bf
    entity_id: binary_sensor.forstofa_hreyfiskynjari
    domain: binary_sensor
    for:
      hours: 0
      minutes: 2
      seconds: 0
  condition: []
  action:
  - type: turn_off
    device_id: 46de38061f6b11eb876355d2445a994b
    entity_id: switch.shelly_shsw_1_8caab50562b4
    domain: switch
  mode: single
