
# Configure a default setup of Home Assistant (frontend, api, etc)
default_config:

# Text to speech
tts:
  - platform: google_translate

# logger:
#   default: warn
#   logs:
#     custom_components.mitemp_bt: debug

media_player:
  - platform: androidtv
    name: TV (Stofa)
    host: 10.0.0.5
#  - platform: androidtv
#    name: TV (Svefnó)
#    host: 10.0.0.7

samsungtv:
  - host: 10.0.0.6



yeelight:
  devices:
    10.0.0.91:
      name: Baðspegill
      transition: 1000
      use_music_mode: true
      save_on_change: true

influxdb:
  host: localhost
  database: home_assistant
  username: !secret influxdb_username
  password: !secret influxdb_password
  max_retries: 3
  default_measurement: state

light: !include lights.yaml
device_tracker: !include devices.yaml
automation: !include automations.yaml
shelly: !include shellies.yaml
ble_monitor: !include xiaomi_ble_sensors.yaml
sensor: !include_dir_merge_list sensors/

group: !include groups.yaml
script: !include scripts.yaml
scene: !include scenes.yaml