
# Configure a default setup of Home Assistant (frontend, api, etc)
default_config:

# Text to speech
tts:
  - platform: google_translate

# logger:
#   default: warn
#   logs:
#     custom_components.mitemp_bt: debug

nissan_leaf:
  username: !secret leaf_username
  password: !secret leaf_password
  region: "NE"
  update_interval:
    minutes: 30
  update_interval_charging:
    minutes: 15
  update_interval_climate:
    minutes: 15
  force_miles: false

media_player:
  - platform: androidtv
    name: TV (Stofa)
    host: 10.0.0.5
    apps: 
      org.samsonsen.radio.island: "Útvarpið"
      is.siminn.tv: "Sjónvarp Símans"
#  - platform: androidtv
#    name: TV (Svefnó)
#    host: 10.0.0.7

yeelight:
  devices:
    10.0.0.91:
      name: Baðspegill
      transition: 1000
      use_music_mode: true
      save_on_change: true

influxdb:
  host: localhost
  database: home_assistant
  username: !secret influxdb_username
  password: !secret influxdb_password
  max_retries: 3
  default_measurement: state

light: !include lights.yaml
device_tracker: !include devices.yaml
automation: !include automations.yaml
shelly: !include shellies.yaml
ble_monitor: !include xiaomi_ble_sensors.yaml
sensor: !include_dir_merge_list sensors/
script: !include scripts.yaml

group: !include groups.yaml
scene: !include scenes.yaml