- platform: mitemp_bt
  mac: '58:2D:34:30:F7:22'
  name: Kids Room Temp
  force_update: true
  median: 1
  monitored_conditions:
    - temperature
    - humidity
    - battery
- platform: mitemp_bt
  mac: '58:2D:34:30:E4:57'
  name: Stofa?
  force_update: true
  median: 1
  monitored_conditions:
    - temperature
    - humidity
    - battery
- platform: mitemp_bt
  mac: '58:2D:34:31:9F:D7'
  name: Elena?
  force_update: true
  median: 1
  monitored_conditions:
    - temperature
    - humidity
    - battery
- platform: mitemp_bt
  mac: '58:2D:34:30:E5:17'
  name: Mía?
  force_update: true
  median: 1
  monitored_conditions:
    - temperature
    - humidity
    - battery
- platform: mitemp_bt
  mac: '58:2D:34:31:A8:D2'
  name: Svefnó?
  force_update: true
  median: 1
  monitored_conditions:
    - temperature
    - humidity
    - battery