- platform: rest
  name: imo_hellisheidi
  scan_interval: 60
  json_attributes_path: "$.[0]"
  json_attributes:
    - id
    - name
    - time
    - link
    - F
    - FX
    - FG
    - D
    - T
    - W
    - V
    - N
    - P
    - RH
    - SNC
    - SND
    - SED
    - RTE
    - TD
    - R
    - err
    - valid
  resource: https://apis.is/weather/observations/is?stations=31392
  value_template: '{{ value_json.results.0.W }}'
- platform: template
  sensors:
    hellisheidi_hitastig:
      friendly_name: "Hitastig"
      value_template: '{{ states.sensor.imo_hellisheidi.attributes["T"] }}'
      device_class: temperature
      unit_of_measurement: '°C'
    hellisheidi_veghiti:
      friendly_name: "Veghiti"
      value_template: '{{ states.sensor.imo_hellisheidi.attributes["RTE"] }}'
      unit_of_measurement: '°C'