- platform: rest
  name: imo_hellisheidi
  scan_interval: 60
  json_attributes_path: "$.[0]"
  json_attributes:
    - id
    - name
    - time
    - link
    - F
    - FX
    - FG
    - D
    - T
    - W
    - V
    - N
    - P
    - RH
    - SNC
    - SND
    - SED
    - RTE
    - TD
    - R
    - err
    - valid
  resource: https://apis.is/weather/observations/is?stations=31392
  value_template: '{{ value_json.results.0.W }}'
- platform: template
  sensors:
    hellisheidi_hitastig:
      friendly_name: "Hitastig"
      value_template: '{{ states.sensor.imo_hellisheidi.attributes["T"] }}'
      device_class: temperature
      unit_of_measurement: '°C'
    hellisheidi_veghiti:
      friendly_name: "Veghiti"
      value_template: '{{ states.sensor.imo_hellisheidi.attributes["RTE"] }}'
      unit_of_measurement: '°C'
    hellisheidi_snjor:
      friendly_name: "Lýsing á snjó"
      value_template: '{{ states.sensor.imo_hellisheidi.attributes["SNC"] }}'
    hellisheidi_snjodypt:
      friendly_name: "Snjódýpt"
      value_template: > 
        {% if state_attr('states.sensor.imo_hellisheidi', 'SND') == None %}
          0
        {% else %}
          {{ state_attr('states.sensor.imo_hellisheidi', 'SND') }}
        {% endif %}
      unit_of_measurement: 'cm'
    hellisheidi_skyggni:
      friendly_name: "Skyggni"
      value_template: >
        {% if state_attr('states.sensor.imo_hellisheidi', 'V') == None %}
          10+
        {% else %}
          '{{ state_attr('states.sensor.imo_hellisheidi', 'V') }}'
        {% endif %}
      unit_of_measurement: 'km'